### ISSUE TITLE
command history - feature request

### ISSUE THREAD

**Issue by noamfree** [bjpop/js-turtle#2]
it would be very nice if one could navigate his previous commands with the "up" and "down" keys, instead of typing again and again.

**Comment by bjpop** [comment]
Thanks @noamfree. Good idea. I probably don't have time to work on this at the moment, but am happy to receive pull requests. Cheers!

**Comment by UInt2048** [comment]
@bjpop, @noamfree, I have implemented this feature in my personal fork. You still will have to copy it from when you have gone up in command history, because hitting "Enter" submits the current command. You are able to copy the last command you typed — to find an error, for example.
Here is the pull request: https://github.com/bjpop/js-turtle/pull/3
